version: '3.8'

services:
  frontend:
    image: hse-frontend:flask-alt
    container_name: frontend
    ports:
    - 5000:5000
    environment:
      API_SERVER_URL: http://traefik:80
    networks:
      - shoppingnet

  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # Uncomment to enable dashboard
      # - "--api.dashboard=true"
    ports:
      - "80:80"
      # Uncomment to expose dashboard
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - shoppingnet

  backend:
    image: hse-backend:springboot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"  # Your backend port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/shoppingdb
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password 
    networks:
      - shoppingnet

  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_DB: shoppingdb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - shoppingnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  shoppingnet:
    external: true
    
